### ISSUE TITLE
UAF support for FIDO2

### ISSUE THREAD

**Issue by Ayush-utd** [StrongKey/FIDO-Server#20]
Hi,
I have installed the FIDO2 server on Ubuntu 18.04 and am running it as a local server.
My plan is to setup a secure connection between my iOS app and the FIDO server using UAF. 
Since UAF isn't supported by FIDO2 (unlike U2F), how do I proceed? 
As far as local authentication is concerned, I am planning to use FaceID and TouchID authentication.
Is there any way I could use FIDO2 for UAF and if so, how do I establish communication with my app?

Thanks in advance.

**Comment by tfvbhy** [comment]
Hello Ayush,
The short answer is that you cannot. Our FIDO Server only supports FIDO2 and U2F. If you are insistent on using the UAF protocol, you will have to find another FIDO server that supports UAF or create your own. 

If you have not started your app, why not use the FIDO2 protocol? FIDO2 is being created as the successor to U2F and UAF.

**Comment by Ayush-utd** [comment]
Thanks for your reply, Michael.
I read online that FIDO2 supports Android currently, and not iOS. Is there any way I could establish a connection between my iOS app and the FIDO2 server?

Also, am I correct in thinking that FIDO2 is best implemented on a web application (client side), and not on a mobile app? I'll be greatly obliged if you could point me towards few resources.

Thank you.

**Comment by arshadnoor** [comment]
Its not just that our FIDO2 server does not support UAF, Ayush - to the best of my knowledge, there is no _open-source_ server that supports UAF and FIDO2 on the same server. 

That said, you need to understand that the FIDO2 protocol was designed to take the best features of U2F and UAF and merge them together into a single protocol.  While FIDO2, functionally, does make that possible, the W3C WebAuthn working group chose to provide backward-compatibility support only for the U2F protocol.  There is some discussion going on in the W3C (which you can find in the WebAuthn mailing lists on the w3c.org site) about providing some layer that can translate UAF to FIDO2 messages.  But, this is still in discussion stage, so I wouldn't expect to see a standard, let alone an implementation of such a standard, anytime in the near future.

The people and companies in the FIDO ecosystem decided to put their energy into standardizing FIDO2 as the protocol that provides the best of U2F and UAF, and that is available right now.  Most of what you want to do with UAF, from a functional point-of-view, can be accomplished with FIDO2; what is missing is likely to show up in the coming years.

My recommendation is to focus on FIDO2 since this is the standard protocol that can be used on mobile devices, tablets, laptops and desktops, etc.  _UAF can only be used on mobile devices._  Yes, I agree there are billions of smartphones on the market today, with many more billions coming.  But, there are also tens of billions of PCs and laptops (in addition to the smartphones) that will not go away, as well as people who will want to use the best device for whatever job they are doing; FIDO2 supports all of those devices today.

Hope that helps.

**Comment by tfvbhy** [comment]
Hello Ayush,
I am currently not aware of resources that describe implementing a mobile flow. However, the general concept remains the same regardless of FIDO protocol/platform. This workflow can be seen on the FIDO Alliances website (https://fidoalliance.org/fido2/):

There are 4 pieces to a FIDO implementation. In these implementations, from my understanding, what you are implementing is the **RP** parts:
1)The authenticator. This is the thing that protects the public/private key pair that performs the cryptographic signing in the FIDO protocol. This either can be an external authenticator (like a Yubikey) or an internal authenticator (like a secure element in your phone).
2)The relying party (RP) Application Client. This is either an app (for a phone) or web application (for a browser).
3)The relying party (RP) App Server. The business logic that manages your users.
4)The FIDO server. This is what StrongKey provides and it performs the cryptographic verification and storage of authenticator public keys.

The pieces fit together like this:
Authenticator<--Webauthn API/Android API/[Proprietary UAF implementations]-->RP Application Client<--RP application API-->RP Application Server<--StrongKey API-->StrongKey FIDO2 Server.

UAF/U2F/FIDO2 define the format of cryptographic messages + describe the interface between the authenticator and the **RP client**.

**Comment by Ayush-utd** [comment]
> Hello Ayush,
> I am currently not aware of resources that describe implementing a mobile flow. However, the general concept remains the same regardless of FIDO protocol/platform. This workflow can be seen on the FIDO Alliances website (https://fidoalliance.org/fido2/):
> 
> There are 4 pieces to a FIDO implementation. In these implementations, from my understanding, what you are implementing is the **RP** parts:
> 1)The authenticator. This is the thing that protects the public/private key pair that performs the cryptographic signing in the FIDO protocol. This either can be an external authenticator (like a Yubikey) or an internal authenticator (like a secure element in your phone).
> 2)The relying party (RP) Application Client. This is either an app (for a phone) or web application (for a browser).
> 3)The relying party (RP) App Server. The business logic that manages your users.
> 4)The FIDO server. This is what StrongKey provides and it performs the cryptographic verification and storage of authenticator public keys.
> 
> The pieces fit together like this:
> Authenticator<--Webauthn API/Android API/[Proprietary UAF implementations]-->RP Application Client<--RP application API-->RP Application Server<--StrongKey API-->StrongKey FIDO2 Server.
> 
> UAF/U2F/FIDO2 define the format of cryptographic messages + describe the interface between the authenticator and the **RP client**.

Thank you for your in-depth response, Michael! Will go through FIDO2 documentation.

**Comment by Ayush-utd** [comment]
> Hello Ayush,
> I am currently not aware of resources that describe implementing a mobile flow. However, the general concept remains the same regardless of FIDO protocol/platform. This workflow can be seen on the FIDO Alliances website (https://fidoalliance.org/fido2/):
> 
> There are 4 pieces to a FIDO implementation. In these implementations, from my understanding, what you are implementing is the **RP** parts:
> 1)The authenticator. This is the thing that protects the public/private key pair that performs the cryptographic signing in the FIDO protocol. This either can be an external authenticator (like a Yubikey) or an internal authenticator (like a secure element in your phone).
> 2)The relying party (RP) Application Client. This is either an app (for a phone) or web application (for a browser).
> 3)The relying party (RP) App Server. The business logic that manages your users.
> 4)The FIDO server. This is what StrongKey provides and it performs the cryptographic verification and storage of authenticator public keys.
> 
> The pieces fit together like this:
> Authenticator<--Webauthn API/Android API/[Proprietary UAF implementations]-->RP Application Client<--RP application API-->RP Application Server<--StrongKey API-->StrongKey FIDO2 Server.
> 
> UAF/U2F/FIDO2 define the format of cryptographic messages + describe the interface between the authenticator and the **RP client**.

Thank you for your detailed response, Arshad! Both your and Michael's responses have brought clarity to my thought process. I will look into FIDO2 and would revert back in case I have any more queries.

Any resources for Android + FIDO2 would be tremendously helpful!
